checkers:
  - name: chartchecker
    type: 'screenshot'
    task: "analyze any charts and tables for common mistakes"
    criteria: |
      - Notes: Check if any part of the chart or table needs clarification.
      - Units: Ensure all units are consistent and appropriate for the data presented.
      - Tagline: Verify that the chart or table has a clear and informative tagline or title (clear slide title is sufficient).
      - Sources: Check if sources are provided where necessary and are properly cited.
      - Axis labels: Confirm that all axes are clearly labeled with appropriate units and scales.
      - Comments: Evaluate if any insights or comments provided are clear and add value to the chart or table.

      Out of scope: The criteria apply ONLY to tables and chart slides. Ignore any other slides.

  - name: spellchecker
    task: "identify spelling and grammar errors, inconsistency, bad punctuation and bad spacing"
    type: 'text'
    criteria: |
      - Spelling: Wrong spelling of common words, ignore any specialized words that can be brands and names
      - Language Consistency: Mix of British and American English in the same text
      - Capitalization: All titles should be title-cased (eg, "Key Message"). For other text, ensure the capitalization is consistent.
      - Punctuation: Wrong use of punctuation marks (eg, "..")
      - Spacing: Double spacing between words, hidden whitespace characters, too many new lines

      Out of scope: Ignore any chart-specific issues, focus purely on the text problems.